Repository hobby-hop/hobby-hop, pull requests merged in 2024-01, with the labels that each got.

#13 Feature/#7 club service
  src/main/java/com/hobbyhop/domain/club/dto/ClubRequestDTO.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubResponseDTO.java
  src/main/java/com/hobbyhop/domain/club/entity/Club.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
Labels: enhancement

#16 Feature/#10 post service
  src/main/java/com/hobbyhop/domain/BaseEntity.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostRequestDTO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/repository/PostRepository.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#17 feat(#15): global exception 구현
  src/main/java/com/hobbyhop/global/exception/common/AuthorizationException.java
  src/main/java/com/hobbyhop/global/exception/common/BusinessException.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorResponse.java
  src/main/java/com/hobbyhop/global/exception/common/GlobalExceptionHandler.java
  src/main/java/com/hobbyhop/global/exception/common/UnAuthorizedModifyException.java
  src/main/java/com/hobbyhop/global/exception/jwt/JwtInvalidException.java
  src/main/java/com/hobbyhop/global/exception/jwt/NoJwtException.java
  src/main/java/com/hobbyhop/global/exception/jwt/UnsupportedGrantTypeException.java
Labels: enhancement

#18 Feature/#7 club service
  build.gradle
  src/main/java/com/hobbyhop/domain/club/dto/ClubResponseDTO.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
Labels: enhancement

#20 feat(#19) : ClubController 작성
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
Labels: enhancement

#22 Feature/#21 category domain
  src/main/java/com/hobbyhop/domain/category/entity/Category.java
  src/main/java/com/hobbyhop/domain/category/enums/HobbyCategory.java
  src/main/java/com/hobbyhop/domain/category/repository/CategoryRepository.java
  src/main/java/com/hobbyhop/domain/category/service/CategoryService.java
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubRequestDTO.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubResponseDTO.java
  src/main/java/com/hobbyhop/domain/club/entity/Club.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/test/java/com/hobbyhop/domain/category/repository/CategoryRepositoryTest.java
Labels: enhancement

#27 test(#21) : 테스트 코드 수정
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
Labels: bug

#30 Feature/#28 cicd
  .github/workflows/check.yml
  .github/workflows/deploy.yml
Labels: documentation

#32 Feature/#29 global response
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/global/response/ApiResponse.java
  src/main/java/com/hobbyhop/global/response/Results.java
Labels: enhancement

#41 fix(#40) : 의도치 않은 변경사항이 dev로 병합되어 발생한 문제 해결
  src/test/java/com/hobbyhop/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/hobbyhop/domain/club/repository/ClubRepositoryTest.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
  src/test/java/com/hobbyhop/domain/cocomment/Cocomment.java
  src/test/java/com/hobbyhop/domain/cocomment/CocommentController.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentErrorCode.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentException.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentRepository.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentRequest.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentResponse.java
  src/test/java/com/hobbyhop/domain/cocomment/CommentService.java
Labels: bug

#42 feat(#14): comment crud 구현
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentListResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/repository/CommentRepository.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
Labels: enhancement

#39 refactor(#37) : 게시글 공통 응답 처리, delete 누락 수정
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
Labels: bug

#43 Fix/#40 bugfix
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: bug

#45 feat(#44): dev#40까지의 exception 추가
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/category/CategoryNotFoundException.java
  src/main/java/com/hobbyhop/global/exception/club/ClubNotFoundException.java
  src/main/java/com/hobbyhop/global/exception/comment/CommentNotFoundException.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/post/PostNotFoundException.java
Labels: enhancement

#35 Feature/user
  build.gradle
  src/main/java/com/hobbyhop/HobbyHopApplication.java
  src/main/java/com/hobbyhop/common/config/AuditingConfig.java
  src/main/java/com/hobbyhop/common/config/WebSecurityConfig.java
  src/main/java/com/hobbyhop/domain/user/constant/UserRoleEnum.java
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/ChangePasswordDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/repository/UserRepository.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/global/security/auth/AuthController.java
  src/main/java/com/hobbyhop/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
  src/main/java/com/hobbyhop/global/security/userdetails/UserDetailsImpl.java
  src/main/java/com/hobbyhop/global/security/userdetails/UserDetailsService.java
  src/main/resources/application.yml
  src/test/java/com/hobbyhop/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/hobbyhop/domain/club/repository/ClubRepositoryTest.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#54 feat(#53): comment 좋아요 추가/취소
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/entity/CommentUser.java
  src/main/java/com/hobbyhop/domain/commentuser/pk/CommentUserPK.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/CommentUserRepository.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/CommentUserRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/CommentUserRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/service/CommentUserService.java
Labels: enhancement

#55 Feature/#31 club pagenation
  build.gradle
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/repository/search/ClubSearch.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubSearchImpl.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/global/request/PageRequestDTO.java
  src/main/java/com/hobbyhop/global/response/PageResponseDTO.java
  src/test/resources/application.yml
Labels: enhancement

#52 Feature/#47 post user
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/post/PostNotCorrespondUser.java
Labels: enhancement

#60 Feature/#56 yml modify
  src/main/resources/application.yml
Labels: documentation

#61 Feature/#51 ClubController
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
Labels: enhancement

#62 Feature/#50 Club Exception
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
Labels: enhancement

#65 Feature/#64 category refactor
  src/main/java/com/hobbyhop/domain/category/controller/CategoryRestController.java
  src/main/java/com/hobbyhop/domain/category/dto/CategoryRequestDTO.java
  src/main/java/com/hobbyhop/domain/category/dto/CategoryResponseDTO.java
  src/main/java/com/hobbyhop/domain/category/entity/Category.java
  src/main/java/com/hobbyhop/domain/category/service/CategoryService.java
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
Labels: enhancement

#66 feat(#33) : 게시글 좋아요 기능 구현
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/domain/postlike/entity/PostLike.java
  src/main/java/com/hobbyhop/domain/postlike/entity/PostLikeKey.java
  src/main/java/com/hobbyhop/domain/postlike/repository/PostLikeRepository.java
  src/main/java/com/hobbyhop/domain/postlike/service/PostLikeService.java
  src/main/java/com/hobbyhop/domain/postlike/service/impl/PostLIkeServiceImpl.java
Labels: enhancement

#71 docs(#70) : application.yml 수정
  src/main/resources/application.yml
Labels: documentation

#72 docs(#70) : test application.yml 수정
  src/test/resources/application.yml
Labels: documentation

#74 refactor(#73): comment sort 구현 (좋아요, 날짜순), 대댓글 sort 추가 예정
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/global/request/SortStandardRequest.java
Labels: enhancement

#78 Feature/#34 post page
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostPageResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/repository/PostRepository.java
  src/main/java/com/hobbyhop/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#80 Feature/#46 social login
  build.gradle
  src/main/java/com/hobbyhop/common/config/RestTemplateConfig.java
  src/main/java/com/hobbyhop/common/config/WebSecurityConfig.java
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/ChangePasswordDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/KakaoUserInfoDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/repository/UserRepository.java
  src/main/java/com/hobbyhop/domain/user/service/KakaoService.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/global/response/ApiResponse.java
  src/main/java/com/hobbyhop/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
  src/main/java/com/hobbyhop/global/security/userdetails/UserDetailsService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement

#86 Feature/#85 modification
  src/main/java/com/hobbyhop/common/config/WebSecurityConfig.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
Labels: enhancement

#81 Feature/#63 club member
  src/main/java/com/hobbyhop/common/config/AuditingConfig.java
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubSearchImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/dto/ClubMemberResponseDTO.java
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/clubmember/ClubMemberNotFoundException.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/request/PageRequestDTO.java
  src/main/java/com/hobbyhop/global/response/PageResponseDTO.java
Labels: enhancement

#83 Feature/#82 swagger config
  src/main/java/com/hobbyhop/common/config/CustomSwaggerConfig.java
  src/main/java/com/hobbyhop/domain/category/controller/CategoryRestController.java
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
Labels: documentation, enhancement

#88 Feature/#87 docker
  .github/workflows/deploy.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#90 Feature/#87 Docker
  .github/workflows/deploy.yml
Labels: documentation

#89 feat(#79) : 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/hobbyhop/common/config/S3Config.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostRequestDTO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/s3/S3Service.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/test/resources/application.yml
Labels: enhancement

#92 Feature/#91 docker test
  .github/workflows/deploy.yml
  Dockerfile
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#94 Feature/#93 reply crd
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/commentreply/entity/CommentReply.java
  src/main/java/com/hobbyhop/domain/commentreply/pk/CommentReplyPK.java
Labels: enhancement

#95 Feature/#84 club request
  src/main/java/com/hobbyhop/domain/club/controller/ClubRestController.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/dto/ClubMemberResponseDTO.java
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/clubmember/enums/MemberRole.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/controller/JoinRequestController.java
  src/main/java/com/hobbyhop/domain/joinrequest/dto/JoinRequestDTO.java
  src/main/java/com/hobbyhop/domain/joinrequest/dto/JoinResponseDTO.java
  src/main/java/com/hobbyhop/domain/joinrequest/entity/JoinRequest.java
  src/main/java/com/hobbyhop/domain/joinrequest/enums/JoinRequestStatus.java
  src/main/java/com/hobbyhop/domain/joinrequest/repository/JoinRequestRepository.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/JoinRequestService.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/clubmember/ClubMemberAlreadyJoined.java
  src/main/java/com/hobbyhop/global/exception/clubmember/ClubMemberRoleException.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/joinrequest/NoSuchRequestException.java
Labels: enhancement

#102 Refactor/#101 common 패키지 삭제, global - config로 이동
  src/main/java/com/hobbyhop/global/config/CustomSwaggerConfig.java
  src/main/java/com/hobbyhop/global/config/RestTemplateConfig.java
  src/main/java/com/hobbyhop/global/config/S3Config.java
  src/main/java/com/hobbyhop/global/config/WebSecurityConfig.java
Labels: documentation

#107 feature(#73): comment sort by reply size
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustomImpl.java
Labels: enhancement

#110 Feature/#109 controller refactor
  src/main/java/com/hobbyhop/domain/category/controller/CategoryController.java
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
Labels: enhancement

#108 refactor(#96) : 컨트롤러단에 스웨거 인증 헤더 설정 추가
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
Labels: documentation, enhancement

#104 Feature/#103 soft delete
  src/main/java/com/hobbyhop/domain/category/entity/Category.java
  src/main/java/com/hobbyhop/domain/club/entity/Club.java
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/joinrequest/entity/JoinRequest.java
Labels: enhancement

#114 fix(#113) : application-prod.yml 수정
  src/main/resources/application-prod.yml
Labels: bug

#115 refactor(#111): comment refactoring
  src/main/java/com/hobbyhop/domain/comment/dto/CommentListResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentVO.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
Labels: enhancement

#116 refactor(#112) : 게시글 리펙토링
  src/main/java/com/hobbyhop/domain/post/repository/PostRepository.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/domain/postlike/repository/PostLikeRepository.java
  src/main/java/com/hobbyhop/domain/postlike/service/impl/PostLIkeServiceImpl.java
  src/main/java/com/hobbyhop/domain/postuser/entity/PostUser.java
  src/main/java/com/hobbyhop/domain/postuser/pk/PostUserPK.java
  src/main/java/com/hobbyhop/domain/postuser/repository/PostUserRepository.java
  src/main/java/com/hobbyhop/domain/postuser/service/PostUserService.java
  src/main/java/com/hobbyhop/domain/postuser/service/impl/PostUserServiceImpl.java
Labels: enhancement

#117 refactor(#112) : PostLikeKey -> PostUserPK로 변경
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/domain/postuser/entity/PostUser.java
  src/main/java/com/hobbyhop/domain/postuser/repository/PostUserRepository.java
  src/main/java/com/hobbyhop/domain/postuser/service/PostUserService.java
  src/main/java/com/hobbyhop/domain/postuser/service/impl/PostUserServiceImpl.java
Labels: bug

#120 refactor(#118) : category refactoring 작업 완료
  src/main/java/com/hobbyhop/domain/category/controller/CategoryController.java
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
Labels: enhancement

#122 Refactor/#121 JoinRequest refactoring
  src/main/java/com/hobbyhop/domain/joinrequest/controller/JoinRequestController.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
Labels: enhancement

#123 Refactor/#119 club member refactoring
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubSearchImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
Labels: enhancement

#129 Refactor/#119 club member refactoring
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/repository/search/ClubRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubSearchImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
Labels: enhancement

#131 refactor(#130) : PostRequestDTO 수정, modifyPost 메서드 수정
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostRequestDTO.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: bug

#127 refactor(#126) : Custom exception handling
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/jwt/ExpiredJwtTokenException.java
  src/main/java/com/hobbyhop/global/exception/jwt/InvalidJwtException.java
  src/main/java/com/hobbyhop/global/exception/jwt/InvalidJwtSignatureException.java
  src/main/java/com/hobbyhop/global/exception/jwt/UnsupportedJwtTokenException.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistEmail.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistUsername.java
  src/main/java/com/hobbyhop/global/exception/user/EmailUnchanged.java
  src/main/java/com/hobbyhop/global/exception/user/MismatchedNewPassword.java
  src/main/java/com/hobbyhop/global/exception/user/MismatchedPassword.java
  src/main/java/com/hobbyhop/global/exception/user/NotFoundUser.java
  src/main/java/com/hobbyhop/global/exception/user/UsernameUnchanged.java
  src/main/java/com/hobbyhop/global/security/auth/AuthController.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#132 feat(#126) : 토큰 유효 시간 증가 및 예외 처리 추가
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/user/MismatchedEmail.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#133 Feature/#125 cors config
  src/main/java/com/hobbyhop/global/config/WebSecurityConfig.java
Labels: enhancement

#135 refactor(#134) : imageUploadPost 기능 분리
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#137 fix(#126) : 토큰 유효 시간 수정(Access : 24h, Refresh : 30days)
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#136 refactor(#119): clubmember에 복합키 적용
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/dto/ClubMemberResponseDTO.java
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/clubmember/pk/ClubMemberPK.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
Labels: enhancement

#138 Feature/#99 post test
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/test/java/com/hobbyhop/domain/post/service/PostServiceTest.java
  src/test/java/com/hobbyhop/test/CategoryTest.java
  src/test/java/com/hobbyhop/test/ClubTest.java
  src/test/java/com/hobbyhop/test/PostTest.java
  src/test/java/com/hobbyhop/test/UserTest.java
Labels: enhancement

#139 feat(#125) : Cors 헤더 반환하도록 수정
  src/main/java/com/hobbyhop/global/config/WebSecurityConfig.java
Labels: enhancement

#142 Refactor/#119 club member refactoring
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
Labels: enhancement

#145 Feature/#144 club validation
  build.gradle
  src/main/java/com/hobbyhop/domain/category/controller/CategoryController.java
  src/main/java/com/hobbyhop/domain/category/dto/CategoryRequestDTO.java
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubRequestDTO.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
Labels: enhancement

#143 Feature/#140 test
  src/test/java/com/hobbyhop/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/hobbyhop/domain/category/service/CategoryServiceTests.java
  src/test/java/com/hobbyhop/domain/club/repository/ClubRepositoryTest.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
  src/test/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImplTest.java
  src/test/java/com/hobbyhop/test/ClubTest.java
Labels: enhancement

#149 feature(#148) : 클럽 전체조회 카테고리 이름 추가
  src/main/java/com/hobbyhop/domain/club/dto/ClubResponseDTO.java
Labels: enhancement

#150 feature(#148) : 클럽 전체조회 카테고리 이름 추가
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubRepositoryCustomImpl.java
Labels: bug

#151 feature(#148) : 클럽 전체조회 카테고리 이름 수정
  src/main/java/com/hobbyhop/domain/club/dto/ClubResponseDTO.java
  src/main/java/com/hobbyhop/domain/club/repository/search/impl/ClubRepositoryCustomImpl.java
Labels: bug

#152 Feature/#99 post test
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/test/java/com/hobbyhop/domain/post/service/impl/PostServiceImplTest.java
  src/test/java/com/hobbyhop/test/UserTest.java
Labels: enhancement

#147 style(#146): Controller에 Operation 적용
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
Labels: enhancement

#156 Refactor/#146 full refactoring
  src/main/java/com/hobbyhop/domain/comment/dto/CommentListResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentVO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostPageResponseDTO.java
  src/main/java/com/hobbyhop/domain/postuser/pk/PostUserPK.java
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/KakaoUserInfoDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/KakaoService.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistEmail.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistEmailException.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistUsernameException.java
  src/main/java/com/hobbyhop/global/exception/user/JsonProcessException.java
  src/main/java/com/hobbyhop/global/exception/user/MismatchedNewPasswordException.java
  src/main/java/com/hobbyhop/global/exception/user/MismatchedPasswordException.java
  src/main/java/com/hobbyhop/global/exception/user/NotFoundUser.java
  src/main/java/com/hobbyhop/global/exception/user/NotFoundUserException.java
Labels: bug

#158 refactor(#157) : @PathVariable 이름 명시
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
Labels: bug

#161 refactor(#160) : 그룹 멤버만 게시글 작성 가능 체크
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#165 refactor(#164) : 게시글 생성 테스트 클럽멤버 추가
  src/test/java/com/hobbyhop/domain/post/service/impl/PostServiceImplTest.java
Labels: enhancement

#166 Refactor/#146 full refactoring
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/common/UnAuthorizedModifyException.java
  src/main/java/com/hobbyhop/global/exception/user/JsonProcessException.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
Labels: bug, enhancement

#163 Feature/#162 category bug fix
  src/main/java/com/hobbyhop/domain/category/repository/CategoryRepository.java
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/category/AlreadyExistCategoryException.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/test/java/com/hobbyhop/domain/category/service/CategoryServiceTests.java
  src/test/java/com/hobbyhop/domain/club/service/ClubServiceTest.java
Labels: bug

#167 Refactor/#146 full refactoring
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/entity/CommentUser.java
  src/main/java/com/hobbyhop/domain/post/s3/S3Service.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/domain/postuser/entity/PostUser.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/s3/ImageSaveException.java
  src/test/java/com/hobbyhop/domain/post/service/impl/PostServiceImplTest.java
Labels: enhancement

#169 refactor(#168) : 게시글 전체 조회 클럽아이디 반환
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
Labels: enhancement

#171 Refactor/#146 full refactoring
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/validCustom/NullablePattern.java
  src/main/java/com/hobbyhop/domain/user/dto/validCustom/NullablePatternValidator.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/test/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImplTest.java
Labels: bug

#173 docs(#172) : redis yml설정
  src/main/resources/application-prod.yml
Labels: documentation

#176 refactor(#175) : 게시글 생성 시 클럽멤버 조회 메서드 버그 수정
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: bug

#174 Refactor/#126 user refactoring
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
Labels: enhancement

#178 Feature/#155 club validation
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/club/AlreadyExistClubTitle.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
Labels: bug

#180 refactor(#179) : 반환 값에 엔티티의 id를 같이 반환하도록 수정
  src/main/java/com/hobbyhop/domain/joinrequest/dto/JoinResponseDTO.java
Labels: enhancement

#181 refactor(#177) : 패키지 명 변경(constant -> enums)
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/enums/UserRoleEnum.java
  src/main/java/com/hobbyhop/domain/user/service/KakaoService.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/global/security/userdetails/UserDetailsImpl.java
  src/test/java/com/hobbyhop/domain/user/service/UserServiceTest.java
Labels: enhancement

#184 Feature/#183 club member refactoring
  .gitignore
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
Labels: enhancement

#186 refactor(#185) : joinrequest response dto 필드에 username 추가
  src/main/java/com/hobbyhop/domain/joinrequest/dto/JoinResponseDTO.java
Labels: enhancement

#189 fix(#188) : comment 컨트롤러 오류 해결
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
Labels: bug

#182 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
Labels: enhancement

#190 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#191 refactor(#177) : KakaoService 인터페이스와 구현체로 나누기
  src/main/java/com/hobbyhop/domain/user/service/KakaoService.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/domain/user/service/impl/KakaoServiceImpl.java
Labels: enhancement

#193 refactor(#192) : ClubRepositoryCustom
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/repository/custom/ClubRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/club/repository/custom/impl/ClubRepositoryCustomImpl.java
Labels: enhancement

#195 Feature/#194 club joinrequest refactor
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/test/java/com/hobbyhop/domain/club/service/impl/ClubServiceImplTest.java
  src/test/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImplTest.java
Labels: enhancement

#196 refactor(#177) : JwtUtil 커스텀 예외처리 완료
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/jwt/InvalidRefreshTokenException.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#199 docs(#198) : ddl-auto none으로 변경
  src/main/resources/application-prod.yml
Labels: documentation

#201 Feature/#200 joinrequest bug fix
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/test/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImplTest.java
Labels: bug

#202 refactor(#177) : UserServiceImpl - @Override 추가
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#203 refactor(#177) : UserServiceImpl - logout 메서드 첫 번째 if 조건문 수정
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#204 Refactor/#177 user refactoring : UserServiceImpl logout 메서드 if 조건문 수정
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#197 refactor(#146): club delete querydsl 적용
  src/main/java/com/hobbyhop/domain/club/dto/ClubElementVO.java
  src/main/java/com/hobbyhop/domain/club/repository/custom/ClubRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/club/repository/custom/impl/ClubRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/hobbyhop/domain/club/service/impl/ClubServiceImplTest.java
Labels: enhancement

#206 Feature/#205 refactor post delete
  src/main/java/com/hobbyhop/domain/club/repository/custom/impl/ClubRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#208 Feature/#205 refactor delete query
  src/main/java/com/hobbyhop/domain/category/dto/CategoryElementVO.java
  src/main/java/com/hobbyhop/domain/category/repository/CategoryRepository.java
  src/main/java/com/hobbyhop/domain/category/repository/custom/CategoryRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/category/repository/custom/impl/CategoryRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/hobbyhop/domain/club/repository/custom/impl/ClubRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/impl/CommentUserRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
  src/test/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImplTests.java
Labels: enhancement

#210 Feature/#209 comment global page dto
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentListResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/CommentRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/service/CommentUserService.java
  src/main/java/com/hobbyhop/domain/commentuser/service/impl/CommentUserServiceImpl.java
  src/main/java/com/hobbyhop/global/request/PageRequestDTO.java
  src/main/java/com/hobbyhop/global/request/SortStandardRequest.java
  src/test/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImplTest.java
Labels: enhancement

#212 refactor(#211) : UserRepository exist 메서드를 fetchFirst로 변경
  src/main/java/com/hobbyhop/domain/user/repository/UserRepository.java
  src/main/java/com/hobbyhop/domain/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/user/repository/custom/impl/UserRepositoryCustomImpl.java
Labels: refactor

#213 Feature/#209 post global page dto
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostPageResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: refactor

#217 fix(#215): comment 조회 오류 수정
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
Labels: bug

#216 Feature/#214 club patch
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubModifyDTO.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/test/java/com/hobbyhop/domain/club/service/impl/ClubServiceImplTest.java
Labels: refactor

#219 Feature/#218 query optimization
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/ClubMemberRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/impl/ClubMemberRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/entity/CommentUser.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/CommentUserRepository.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/CommentUserRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/impl/CommentUserRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/commentuser/service/impl/CommentUserServiceImpl.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/postuser/entity/PostUser.java
Labels: enhancement

#221 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#223 refactor(#220) : 게시글 수정 요청 DTO 분리
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/dto/PostModifyRequestDTO.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: refactor

#225 refactor(#224) : 게시글 entity imageUrl 변경
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
Labels: refactor

#227 feature(#226) : 게시글 키워드 조회 기능 추가
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: enhancement

#228 refactor(#226) : 게시글 키워드 조회 GetMapping과 내부 쿼리 수정
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: bug

#229 refactor(#224) : 엔티티 길이 수정
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: refactor

#230 refactor(#224) : 게시글 삭제 admin 삭제
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: refactor

#231 refactor(#224) : 게시글 수정 RequestParam 수정
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
Labels: refactor

#232 refactor(#224) : 게시글 수정 null check 수정
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: bug

#233 Refactor/#222 security refactoring
  src/main/java/com/hobbyhop/global/security/jwt/JwtUtil.java
Labels: enhancement

#235 Feature/#234 profile view
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/MyProfileResponseDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#238 Feature/#234 profile view
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/OtherProfileResponseDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#239 Feature/#237 withdrawal
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/WithdrawalRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/UserService.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: enhancement

#241 Feature/#240 club create validation
  src/main/java/com/hobbyhop/domain/club/dto/ClubModifyDTO.java
  src/main/java/com/hobbyhop/domain/club/dto/ClubRequestDTO.java
Labels: refactor

#244 Feature/#242 joinreuqest bug fix
  src/main/java/com/hobbyhop/domain/joinrequest/repository/JoinRequestRepository.java
  src/main/java/com/hobbyhop/domain/joinrequest/repository/custom/JoinRequestRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/joinrequest/repository/custom/impl/JoinRequestRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/joinrequest/PendingRequest.java
Labels: bug

#243 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/controller/UserController.java
  src/main/java/com/hobbyhop/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/user/NotAvailableEmail.java
  src/main/java/com/hobbyhop/global/exception/user/NotAvailableUsername.java
  src/main/java/com/hobbyhop/global/exception/user/SignupBlankException.java
Labels: enhancement

#246 Feature/#245 club paging
  src/main/java/com/hobbyhop/domain/club/repository/custom/impl/ClubRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/global/response/PageResponseDTO.java
Labels: bug

#248 Feature/#247 comment pathvariable declare
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/CommentUserRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/commentuser/repository/custom/impl/CommentUserRepositoryCustomImpl.java
Labels: enhancement

#249 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/repository/UserRepository.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/user/AlreadyExistUserException.java
  src/main/java/com/hobbyhop/global/exception/user/DuplicateEntryException.java
  src/main/java/com/hobbyhop/global/exception/user/NotAvailableEmailException.java
  src/main/java/com/hobbyhop/global/exception/user/NotAvailableUsernameException.java
Labels: enhancement

#254 Refactor/#253 post get from clubmember
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/test/java/com/hobbyhop/domain/post/service/impl/PostServiceImplTest.java
Labels: refactor

#257 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
Labels: enhancement

#258 Refactor/#177 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/MyProfileResponseDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/OtherProfileResponseDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/user/MatchedPasswordException.java
Labels: enhancement

#260 Refactor/#259 post refactor
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/domain/post/service/PostService.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
Labels: refactor

#269 Refactor/#268 post tile content limit setting
  src/main/java/com/hobbyhop/domain/post/dto/PostModifyRequestDTO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostRequestDTO.java
Labels: refactor

#263 refector(#262): comment id 반환 추가
  src/main/java/com/hobbyhop/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
Labels: enhancement

#270 Feature/#265 member check api
  src/main/java/com/hobbyhop/domain/clubmember/controller/ClubMemberController.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/ClubMemberRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/impl/ClubMemberRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
Labels: enhancement

#271 Refactor/#268 post modify @Notblack delete
  src/main/java/com/hobbyhop/domain/post/dto/PostModifyRequestDTO.java
Labels: refactor

#267 Feature/#266 user info
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
Labels: bug

#274 Refactor/#272 PostResponseDTO username -> writer
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
Labels: refactor

#276 refactor(#275) : 프로필 정보 변경 수정(info, password 만 수정 가능)
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#278 Feature/#277 user update fix
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: bug
