Repository hobby-hop/hobby-hop, pull requests merged in 2024-02, with the labels that each got.

#279 Feature/#277 user update fix
  src/main/java/com/hobbyhop/domain/user/entity/User.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: bug

#281 fix(#280) : 패스워드 수정 오류 수정
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: bug

#285 Refactor/#284 PostPageResponseDTO username -> writer
  src/main/java/com/hobbyhop/domain/post/dto/PostPageResponseDTO.java
Labels: refactor

#287 Refactor/#286 post numbering
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/service/ClubService.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/post/dto/PostPageResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/dto/PostResponseDTO.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/post/service/impl/PostServiceImpl.java
Labels: refactor

#288 Refactor/#286 post numbering querydsl
  src/main/java/com/hobbyhop/domain/post/repository/custom/impl/PostRepositoryCustomImpl.java
Labels: refactor

#283 Refactor/#282 user refactoring
  src/main/java/com/hobbyhop/domain/user/dto/SignupRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/dto/UpdateProfileRequestDTO.java
  src/main/java/com/hobbyhop/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#295 Feature/#291 club refactoring
  src/main/java/com/hobbyhop/domain/club/repository/ClubRepository.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/ClubMemberRepositoryCustom.java
  src/main/java/com/hobbyhop/domain/clubmember/repository/custom/impl/ClubMemberRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/ClubMemberService.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/main/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImpl.java
  src/main/java/com/hobbyhop/global/exception/common/ErrorCode.java
  src/main/java/com/hobbyhop/global/exception/joinrequest/JoiningClubCountExceed.java
Labels: refactor

#297 Feature/#294 post service testcode
  src/main/resources/images/image1.jpg
  src/test/java/com/hobbyhop/domain/post/service/impl/PostServiceImplTest.java
  src/test/java/com/hobbyhop/test/PostTest.java
  src/test/java/com/hobbyhop/test/UserTest.java
Labels: enhancement

#293 Fix/#292 change deprecated api
  src/main/java/com/hobbyhop/domain/category/entity/Category.java
  src/main/java/com/hobbyhop/domain/club/entity/Club.java
  src/main/java/com/hobbyhop/domain/clubmember/entity/ClubMember.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/commentuser/entity/CommentUser.java
  src/main/java/com/hobbyhop/domain/joinrequest/entity/JoinRequest.java
  src/main/java/com/hobbyhop/domain/post/entity/Post.java
  src/main/java/com/hobbyhop/domain/postuser/entity/PostUser.java
  src/main/java/com/hobbyhop/domain/user/entity/User.java
Labels: refactor

#300 Feature/#141 comment test
  src/main/java/com/hobbyhop/domain/comment/controller/CommentController.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentPageRequestDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/hobbyhop/domain/comment/dto/CommentResponseDTO.java
  src/main/java/com/hobbyhop/domain/comment/entity/Comment.java
  src/main/java/com/hobbyhop/domain/comment/repository/custom/impl/CommentRepositoryCustomImpl.java
  src/main/java/com/hobbyhop/domain/comment/service/CommentService.java
  src/main/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/hobbyhop/global/request/PageRequestDTO.java
  src/test/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/hobbyhop/test/CommentTest.java
Labels: enhancement

#298 Feature/#140 test
  src/main/java/com/hobbyhop/domain/category/repository/CategoryRepository.java
  src/main/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/hobbyhop/domain/club/service/impl/ClubServiceImpl.java
  src/main/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImpl.java
  src/test/java/com/hobbyhop/domain/category/service/impl/CategoryServiceImplTests.java
  src/test/java/com/hobbyhop/domain/club/service/impl/ClubServiceImplTest.java
  src/test/java/com/hobbyhop/domain/clubmember/service/impl/ClubMemberServiceImplTest.java
  src/test/java/com/hobbyhop/domain/joinrequest/service/impl/JoinRequestServiceImplTest.java
Labels: enhancement

#304 Feature/#303 security permit
  src/main/java/com/hobbyhop/domain/club/controller/ClubController.java
  src/main/java/com/hobbyhop/domain/post/controller/PostController.java
  src/main/java/com/hobbyhop/global/config/WebSecurityConfig.java
  src/test/java/com/hobbyhop/domain/comment/service/impl/CommentServiceImplTest.java
Labels: enhancement
